id = "flutter-snippets"
name = "Flutter Snippets"
version = "0.2.0"
schema_version = 1
authors = ["lsdanii <luisdanieldlcg@gmail.com>"]
description = "A collection of Flutter snippets to improve your development speed."
repository = "https://github.com/luisdanieldlcg/flutter-snippets"
snippets = "./snippets/dart.json"
